import {ACTIONS,CHALLENGES,ENDINGS,createGame,advanceMonth,resolveEvent,solveChallenge,getEnding,serialize,deserialize} from './engine.js';
const $=id=>document.getElementById(id),el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const SAVE='tamsui-four-years-v1',AUTO=SAVE+'-auto';let game=createGame(Math.floor(Math.random()*2147483646)+1),plan=['study','code','rest'],slot=0,busy=false,music=false,audio,timer,toastTimer;
const labels={study:'課業',code:'程式',social:'社交',fitness:'體能',health:'健康',stress:'壓力',money:'預算'};
const years=['大一','大二','大三','大四'];const chapters=[['初來乍到','新的日常，正在發芽。'],['找到節奏','在嘗試裡，找到喜歡的事。'],['走向世界','把想像，寫成真實的作品。'],['此刻與以後','帶著這些日子，走向下一站。']];
function toast(t){$('toast').textContent=t;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3200)}
function store(key,silent=false){try{localStorage.setItem(key,serialize(game));if(!silent)toast('已儲存。目前的選擇，會在這裡等你。');return true}catch(e){toast('此瀏覽器無法儲存進度，請勿關閉分頁。');return false}}
function safeRun(fn){try{fn()}catch(e){toast(e.message||'這一步暫時無法完成。')}}
function effects(e){return Object.entries(e).filter(([,v])=>v).map(([k,v])=>`${labels[k]||k} ${v>0?'+':''}${v}`).join(' · ')}
function button(text,fn,cls=''){const b=el('button',cls,text);b.type='button';b.onclick=fn;return b}
function openModal(title,eyebrow='四年練習曲',dismiss=true){const d=$('modal'),b=$('modalBody');b.replaceChildren();b.append(el('p','eyebrow',eyebrow));const h=el('h2','',title);h.id='modalTitle';b.append(h);d.oncancel=e=>{if(!dismiss)e.preventDefault()};if(!d.open)d.showModal();return b}
function close(){ $('modal').close() }
function closeButton(b,text='回到校園'){const row=el('div','dialog-actions');row.append(button(text,close,'primary'));b.append(row)}
function render(){const y=Math.min(3,Math.floor(game.month/12)),sem=Math.min(8,Math.floor(game.month/6)+1);$('yearLabel').textContent=`${years[y]} · ${sem%2?'上':'下'}學期`;$('monthLabel').textContent=game.finished?'畢業這一天':`第 ${Math.min(48,game.month+1)} 個月`;$('ageLabel').textContent=`${18+y} 歲 / 淡江資工`;$('progressLabel').textContent=`${game.month} / 48 個月`;$('timeline').replaceChildren(...Array.from({length:8},(_,i)=>el('i',i<Math.floor(game.month/6)?'complete':i===Math.floor(game.month/6)?'active':'')));
$('chapterLabel').textContent=`CHAPTER 0${y+1} / ${chapters[y][0]}`;$('chapterTitle').textContent=chapters[y][1];$('season').textContent=['微風入學季','秋日慢生活','冬陽與熱茶','春日練習題'][Math.floor(game.month%12/3)];$('mood').textContent=game.stats.stress>70?'「累的時候，慢一點也沒關係。」':game.stats.code>65?'「原來，我也能把想法做出來。」':'「先走出第一步，答案會慢慢出現。」';
$('stats').replaceChildren(...Object.entries(game.stats).filter(([k])=>k!=='money').map(([k,v])=>{const d=el('div',`stat ${k}`),head=el('div','stat-head');head.append(el('span','',labels[k]+(k==='stress'?' ↓':'')),el('strong','',`${v}`));const bar=el('div','bar'),fill=el('i');fill.style.width=v+'%';bar.append(fill);bar.setAttribute('role','meter');bar.setAttribute('aria-label',labels[k]);bar.setAttribute('aria-valuemin','0');bar.setAttribute('aria-valuemax','100');bar.setAttribute('aria-valuenow',v);d.append(head,bar);return d}));$('money').textContent='$ '+game.stats.money.toLocaleString();$('projectCount').textContent=`${game.projects.completed} 件完成`;$('projectProgress').value=game.projects.progress;$('projectProgress').setAttribute('aria-label','專題完成進度');$('projectHint').textContent=`下一件作品 ${game.projects.progress}% · 安排專題可推進里程碑`;
$('friends').replaceChildren(...game.relationships.map((f,i)=>{const d=el('div','friend'),p=el('div','portrait'),info=el('div','friend-info');p.style.backgroundPosition=['100% 0','0 100%','100% 100%'][i];p.setAttribute('role','img');p.setAttribute('aria-label',f.name+'的原創插畫');const name=el('strong','',f.name);name.append(el('span','affinity',`♥ ${f.affinity}`));info.append(name,el('p','',f.role));const bar=el('div','bar'),fill=el('i');fill.style.width=f.affinity+'%';bar.append(fill);info.append(bar);d.append(p,info);return d}));
$('logs').replaceChildren(...(game.logs.length?game.logs.slice(0,5):[{month:0,text:'帶著一只背包，來到有風的校園。這一次，日程由自己安排。'}]).map(l=>{const d=el('div','log');d.append(el('small','',l.month?`第 ${l.month} 個月`:'入學日'),el('p','',l.text));return d}));renderPlan();$('advance').disabled=game.finished||!!game.pendingEvent||busy;$('advance').textContent=game.finished?'查看畢業結局':game.pendingEvent?'先完成生活事件':'開始這個月 ▶';if(game.finished)$('advance').disabled=false;$('challenge').disabled=game.finished||!!game.pendingEvent||game.challengeSolved.includes(sem);$('challenge').textContent=game.challengeSolved.includes(sem)?'本學期已挑戰':'接受挑戰';$('challengeTitle').textContent=CHALLENGES[sem-1].title;}
function renderPlan(){const focused=document.activeElement?.getAttribute('aria-label');const disabled=game.finished||!!game.pendingEvent; $('plan').replaceChildren(...plan.map((a,i)=>{const b=button('',()=>{slot=i;renderPlan()},`plan-slot ${slot===i?'selected':''}`);b.disabled=disabled;b.setAttribute('aria-pressed',String(slot===i));b.setAttribute('aria-label',`時段${i+1}：${ACTIONS[a].name}`);b.append(el('small','', ['月初 · 第一個重心','月中 · 第二個重心','月底 · 第三個重心'][i]),el('strong','',`${ACTIONS[a].icon} ${ACTIONS[a].name}`),el('span','number',`0${i+1}`));return b}));$('actions').replaceChildren(...Object.values(ACTIONS).map(a=>{const b=button('',()=>{plan[slot]=a.id;slot=(slot+1)%3;renderPlan()},`activity ${plan.includes(a.id)?'selected':''}`);b.title=a.desc;b.setAttribute('aria-label',a.name+'，'+effects(a.effects));b.disabled=disabled||(a.minYear&&Math.floor(game.month/12)+1<a.minYear);const title=el('strong');title.append(el('span','activity-icon',a.icon),document.createTextNode(a.name));b.append(title,el('span','effects',a.minYear&&game.month<24?'大三起開放':effects(a.effects)));return b}));document.querySelectorAll('[data-preset]').forEach(b=>b.disabled=disabled);if(focused){const target=[...document.querySelectorAll('#plan button,#actions button')].find(b=>b.getAttribute('aria-label')===focused);if(target&&!target.disabled)target.focus({preventScroll:true})}}
function eventModal(){const e=game.pendingEvent;if(!e)return;const b=openModal(e.title,e.category+' · 第 '+game.month+' 個月',false);b.append(el('p','',e.text));for(const [i,o]of e.options.entries()){const btn=button(o.label,()=>safeRun(()=>{game=resolveEvent(game,i);close();store(AUTO,true);render();if(game.finished)endingModal()}),'choice');btn.append(el('small','',effects(o.effects)));b.append(btn)}}
function endingModal(){const end=getEnding(game);if(!end)return;const b=openModal(end.title,'GRADUATION / 48 MONTHS OF YOU');b.append(el('p','',end.subtitle),el('p','',end.description),el('p','muted',`八學期平均 ${end.averageGrade} 分 · 完成 ${game.projects.completed} 件作品`));if(end.achievements?.length)b.append(el('p','',end.achievements.join(' · ')));b.append(el('p','muted','你的畢業不是句點。每一種生活，都有值得帶走的事。'));const row=el('div','dialog-actions');row.append(button('留在畢業日',close),button('再過另一種四年',restart,'primary'));b.append(row)}
$('advance').onclick=()=>safeRun(()=>{if(game.finished)return endingModal();if(busy||game.pendingEvent)return;busy=true;game=advanceMonth(game,plan);store(AUTO,true);render();setTimeout(()=>{busy=false;render()},450);if(game.pendingEvent)eventModal();else if(game.finished)endingModal();else toast(`第 ${game.month} 個月完成，翻開下一頁。`)});
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{plan=({balanced:['study','code','rest'],developer:['code','project','exercise'],recovery:['rest','exercise','social']})[b.dataset.preset].slice();slot=0;renderPlan();toast('日程已更新，仍可逐格調整。')});
$('save').onclick=()=>store(SAVE);$('load').onclick=()=>{let manual,auto;try{manual=localStorage.getItem(SAVE);auto=localStorage.getItem(AUTO)}catch{toast('此瀏覽器無法讀取存檔。');return}if(!manual&&!auto){toast('還沒有存檔。完成第一個月後會自動儲存。');return}const b=openModal('回到存下的那一天','讀取進度');b.append(el('p','', '讀檔會取代目前進度。取消則不變更。'));for(const [name,data]of [['手動存檔',manual],['自動存檔',auto]])if(data){let preview;try{preview=deserialize(data)}catch{b.append(el('p','',name+'已損壞，無法載入；目前進度不受影響。'));continue}b.append(button(`${name} · 已過 ${preview.month} 個月`,()=>safeRun(()=>{game=deserialize(data);busy=false;close();render();toast('進度已讀取。');if(game.pendingEvent)eventModal();else if(game.finished)endingModal()}),'choice'))}closeButton(b,'取消');};
function restart(){const b=openModal('重新出發？','另一段四年');b.append(el('p','', '目前遊戲會重新開始，自動存檔將被新旅程取代。手動存檔會保留，直到你再次按下存檔。'));const row=el('div','dialog-actions');row.append(button('取消',()=>{close();if(game.pendingEvent)eventModal()}),button('確定重新開始',()=>{game=createGame(Math.floor(Math.random()*2147483646)+1);plan=['study','code','rest'];slot=0;busy=false;close();store(AUTO,true);render();toast('新學年，新的一頁。')},'primary'));b.append(row)}$('restart').onclick=restart;
$('challenge').onclick=()=>{const c=CHALLENGES[Math.min(7,Math.floor(game.month/6))],b=openModal(c.title,'本學期一次 · 無時間限制');b.append(el('p','',c.prompt));c.options.forEach((o,i)=>b.append(button(o,()=>safeRun(()=>{game=solveChallenge(game,i);store(AUTO,true);render();const body=openModal(i===c.answer?'解題成功！':'多學到了一點','每次思考，都有收穫');body.append(el('p','',c.explanation),el('p','muted',i===c.answer?'程式 +5 · 課業 +2':'程式 +1'));closeButton(body)}),'choice')));closeButton(b,'先不挑戰')};
$('endings').onclick=()=>{const b=openModal('你想走向哪裡？','畢業方向 · 同時符合時依下列順序決定');for(const e of ENDINGS){const row=el('div','ending-row');row.append(el('strong','',e.title),el('small','',e.conditions));b.append(row)}closeButton(b)};
$('history').onclick=()=>{const b=openModal('八個學期的足跡','學期成績');if(!game.semesters.length)b.append(el('p','', '每六個月結算一次學期成績。現在還有很多可以嘗試的事。'));for(const s of game.semesters){const row=el('div','ending-row');row.append(el('strong','',`第 ${s.semester} 學期 · ${s.grade} 分 · ${s.label}`),el('small','',s.note));b.append(row)}closeButton(b)};
$('help').onclick=()=>{const b=openModal('歡迎來到，你的四年。','HOW TO PLAY');for(const t of ['你是 18 歲的虛構學生姜彥廷。遊戲共 48 個月、8 個學期；每月安排三個活動，約 20–35 分鐘走完一輪。','點選日程中的時段，再選下方活動。活動依序執行；先休息再學習，有時比一口氣衝刺更有效。數字是基本變化，身體狀態與事件也會影響結果。','每月支持 3,000、生活費 2,800。打工補充預算；專題與實習累積作品。資源不足時有緊急協助，健康過低會自動恢復，不會卡死，但高壓會影響學習。','每學期一次無計時解題挑戰。生活事件需要選擇；沒有唯一正解。社團、相處與運動能培養不同的夥伴關係。','完成一個月會自動存檔；工具列「存檔」另外保留手動進度。讀檔可選兩種，重開保留手動存檔。清除瀏覽器資料將刪除存檔，不跨裝置同步。','本作僅參考排程養成的抽象機制；人物、美術、情節、音樂與程式皆原創。校園與教育制度為架空遊戲設定，非校方官方產品。'])b.append(el('p','',t));closeButton(b,'開始我的日常')};
function playTone(freq,start,duration,volume=.04){const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;o.connect(g);g.connect(audio.destination);g.gain.setValueAtTime(0,start);g.gain.linearRampToValueAtTime(volume,start+.04);g.gain.exponentialRampToValueAtTime(.001,start+duration);o.start(start);o.stop(start+duration+.03)}
function phrase(){if(!music||!audio)return;const notes=[261.63,329.63,392,440,392,329.63,293.66,329.63,261.63,293.66,349.23,392,349.23,293.66,261.63,196];notes.forEach((n,i)=>playTone(n,audio.currentTime+i*.42,.72));[130.81,164.81,146.83,174.61].forEach((n,i)=>playTone(n,audio.currentTime+i*1.68,1.5,.022))}
$('sound').onclick=async()=>{try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();music=!music;if(music){await audio.resume();if(!music)return;clearInterval(timer);phrase();timer=setInterval(phrase,6720)}else{clearInterval(timer);await audio.suspend()}$('sound').textContent=music?'♫ 音樂開':'♫ 音樂關';$('sound').setAttribute('aria-pressed',String(music))}catch{music=false;toast('此瀏覽器暫時無法播放音樂。')}};
document.addEventListener('visibilitychange',()=>{if(!audio||!music)return;if(document.hidden){clearInterval(timer);audio.suspend()}else{clearInterval(timer);audio.resume().then(()=>{if(!music||document.hidden)return;clearInterval(timer);phrase();timer=setInterval(phrase,6720)})}});
render();
try{const saved=localStorage.getItem(AUTO);if(saved){const loaded=deserialize(saved);const b=openModal('歡迎回到有風的校園','已找到本機進度');b.append(el('p','',`你的故事停在第 ${loaded.month} 個月。要從那裡繼續嗎？`));const row=el('div','dialog-actions');row.append(button('先看看新日程',close),button('繼續我的故事',()=>{game=loaded;close();render();if(game.pendingEvent)eventModal();else if(game.finished)endingModal()},'primary'));b.append(row)}}catch{toast('自動存檔無法讀取，已安全開啟新遊戲；舊檔尚未覆蓋。')}
